### ISSUE TITLE
Problem with drush in netbeans 7.4 on linux mint.

### ISSUE THREAD

**Issue by prabhatjn** [tusharvjoshi/NBDrupalDevel#33]
Hi,

Can someone please tell me what am I doing wrong seeing the clipboard.

Thanks,
P.
![image](https://f.cloud.github.com/assets/693849/1680878/4946c302-5d86-11e3-9383-cba983e3dd63.png)

**Comment by agilis1** [comment]
This is the exactly the issue I'm having. The drush output in NetBeans says EXECUTE but it never finishes. Looking the NetBeans IDE log, yields the following:

`java.io.IOException: Cannot run program "--root="/home/agilis/PublicHtml/DrupalTestBase/webroot"" (in directory "/usr/local/src/drush"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.netbeans.modules.php.drupaldevel.drush.ui.CommandProcessor$CommandRunner.runCommand(CommandProcessor.java:250)
	at org.netbeans.modules.php.drupaldevel.drush.ui.CommandProcessor.runCommand(CommandProcessor.java:144)
	at org.netbeans.modules.php.drupaldevel.drush.ui.DrushTopComponent.executeDrush(DrushTopComponent.java:191)
	at org.netbeans.modules.php.drupaldevel.drush.ui.DrushTopComponent.commandParse(DrushTopComponent.java:116)
	at org.netbeans.modules.php.drupaldevel.drush.ui.DrushTopComponent$3.commandEnter(DrushTopComponent.java:94)
	at org.netbeans.modules.php.drupaldevel.drush.ui.CommandHistory.fireEnterCommandHistoryEvent(CommandHistory.java:187)
	at org.netbeans.modules.php.drupaldevel.drush.ui.CommandHistory.access$600(CommandHistory.java:22)
	at org.netbeans.modules.php.drupaldevel.drush.ui.CommandHistory$1.keyPressed(CommandHistory.java:64)
	at java.awt.Component.processKeyEvent(Component.java:6493)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 43 more`

The main error being: 
'java.io.IOException: Cannot run program "--root="/home/agilis/PublicHtml/DrupalTestBase/webroot"" (in directory "/usr/local/src/drush"): error=2, No such file or directory'

I have tried to manually specify the Drupal root path as well let the Drupal Developer plugin determine the root path on its own. Same error.

Cannot use drush.

**Comment by silkentrance** [comment]
This is a duplicate of / similar issue to #21. See https://github.com/tusharvjoshi/NBDrupalDevel/issues/21#issuecomment-244568008
